# Find all test results from a particular samplepoint, their associated observation, sample, analyzed substance (using DSSToxIDs) and result. 
# This is limited to samples whose substance is mapped to DSSTox chemicals

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX spatial: <http://purl.org/spatialai/spatial/spatial-full#>

PREFIX coso: <http://w3id.org/coso/v1/contaminoso#>
PREFIX dsstox: <http://w3id.org/DSSTox/v1/>

SELECT * WHERE {
    # Find all samples and their results from a particular samplePoint
   ?samp_pt rdf:type coso:SamplePoint .
        VALUES ?samp_pt{<http://w3id.org/sawgraph/v1/me-egad-data#samplePoint.94300>} 
  ?obs coso:observedAtSamplePoint ?samp_pt;
		coso:analyzedSample ?sample;
        coso:ofSubstance ?substance;
        coso:hasResult ?result.
  ?substance rdf:type dsstox:ChemicalEntity ;
        skos:altLabel ?substanceLabel.
  ?result coso:measurementValue ?quantity.
} 